apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 5Gi                     # Kapasitas PV
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo            # Lokasi di host (Minikube)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
