apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo-service"       # Harus sama dengan Service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME  # Mount secret
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /data/db               # Mount PV
        - name: config
          mountPath: /config                # Mount ConfigMap
        - name: credentials
          mountPath: /etc/mongo-credentials # Mount Secret
      volumes:
      - name: config
        configMap:
          name: mongo-config
      - name: credentials
        secret:
          secretName: mongo-secret
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
